### PR TITLE
Fixes compatibility with symfony 3.0

### PR DESCRIPTION
**Pull request by ottovw**

### CODE REVIEW

**Comment by ddeboer** [comment]
Will this still work on Symfony < 3.0?

**Comment by antoligy** [comment]
If not, tag as a major version?

**Comment by ottovw** [comment]
@ddeboer i don't think so, but I'm not totally sure. but the current version doesn't work with symfony 3 due to this one line

**Comment by ThierryCols** [comment]
Hi @ddeboer, 
Is there anything that would prevent merging that PR?

**Comment by aistis-** [comment]
Also waiting for the fix.

**Review by aistis- — APPROVED** [review]

**Comment by aistis-** [comment]
@ddeboer Could you merge the fix? It is compatible with Symfony 2.6+

**Comment by aistis-** [comment]
@ddeboer Ping ping :cry:

**Pull request merged**
